library(desc)
descript <- desc::desc(file = "DESCRIPTION")
# descript$set("Version", app_version)
descript$set("Version", "1.0.7")
descript$write()
rm(descript)
usethis::use_build_ignore(c("version"))
